version: '2'
services:
  app:
    restart: always
    build: .
    volumes:
      - ./app/:/code/
    links:
      - postgres:postgres
    ports:
      - "9000:9000"
    expose:
      - "9000"
    env_file: .env
    command: python manage.py runserver 0.0.0.0:9000
  nginx:
    image: nginx
    volumes:
     - ./mysite.conf:/etc/nginx/conf.d/mysite.template
    ports:
     - "80:80"
    links:
      - app
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  postgres:
    restart: always
    image: postgres
    ports:
      - "5432:5432"
